### ISSUE TITLE
Possibly XML Parse Error

### ISSUE THREAD

**Issue by QYL** [Sneezry/Kepler#1]
Saw this error which appears on every page:

> This page contains the following errors:
> 
>     error on line 9 at column 210: Opening and ending tag mismatch: br line 0 and P
> 
> Below is a rendering of the page up to the first error.

**Comment by Sneezry** [comment]
please try the latest code to see if this issue has been fixed

**Comment by QYL** [comment]
No more errors, but all the images within the book are disappeared.

**Comment by Sneezry** [comment]
Image missing is caused by hardcode image path. The previous code uses assist folder to save images, which should be parsed from TOC file. I have pushed a new commit to fix this bug.

**Comment by QYL** [comment]
Works like a charm. Thanks a million.
